### ISSUE TITLE
Getting an error while running `peanut` command

### ISSUE THREAD

**Issue by piedcipher** [kevmoo/peanut.dart#101]
Could not find a file named "pubspec.yaml" in "/home/tirth/.pub-cache/hosted/pub.dartlang.org/boolean_selector-2.1.0".

**Comment by kevmoo** [comment]
Oh. Looks like you need to run `pub get` again!

**Comment by piedcipher** [comment]
Tried `flutter pub get` again, got same error.

**Comment by piedcipher** [comment]
I checked `.pub-cache/....` path, there are 2 boolean_selector:

```
boolean_selector-2.0.0/              boolean_selector-2.1.0-nullsafety.1/ 
```

Not the `boolean_selector-2.1.0`

**Comment by piedcipher** [comment]
Why you closed the issue? Any help would be appreciated.

**Comment by piedcipher** [comment]
Btw I'm not using boolean_selector in my app, it shows error when running peanut.

**Comment by kevmoo** [comment]
Try re-running `pub global activate peanut`?

What's the full stack trace?

**Comment by piedcipher** [comment]
Tried re-running already. I only get that single line error.

> I checked `.pub-cache/....` path, there are 2 boolean_selector:
> 
> ```
> boolean_selector-2.0.0/              boolean_selector-2.1.0-nullsafety.1/ 
> ```
> 
> Not the `boolean_selector-2.1.0`

This seems like the issue to me. There is no folder named `boolean_selector-2.1.0/` but there is `boolean_selector-2.1.0-nullsafety.1/ `

**Comment by piedcipher** [comment]
`flutter build web` is much better than penaut.

**Comment by kevmoo** [comment]
> `flutter build web` is much better than penaut.

`flutter build web` is the base tool that most folks should use.

`peanut` tried to do a very specific thing. Please let me know if it's not working for you.

**Comment by gisborne** [comment]
I am having this problem.
