### ISSUE TITLE
The gh pages repo becomes very heavy after 2-3 times run peanut

### ISSUE THREAD

**Issue by gauravmehta13** [kevmoo/peanut.dart#105]

**Comment by gauravmehta13** [comment]
![image](https://user-images.githubusercontent.com/51997260/112713199-0ca46280-8efa-11eb-95ac-31d277794bc3.png)
had to upload somethimes 500-600 mbs of data

**Comment by kevmoo** [comment]
There must be a lot of none-Dart content in your packages.

You should be able to see what's included in the output by looking at
GitHub.

You can specify a --post-build-dart-script to remove files during a peanut
run
