### ISSUE TITLE
Support Windows with build_runner

### ISSUE THREAD

**Issue by kevmoo** [kevmoo/peanut.dart#11]
Currently using `cp` and `mkdir` – likely won't work on Windows.

**Comment by denniskaselow** [comment]
I can confirm that it works on windows (https://github.com/kevmoo/peanut.dart/commit/57fa00720b1b9604b129c063e3cdbcf5ad949f46).

**Comment by kevmoo** [comment]
Awesome! Thanks for letting me know!

**Comment by jakemac53** [comment]
Yep I can confirm as well!

**Comment by kevmoo** [comment]
🤘
