### ISSUE TITLE
Build failing while using in mixed mode

### ISSUE THREAD

**Issue by madhavtripathi05** [kevmoo/peanut.dart#110]
Please add a flag for ```--no-sound-null-safety``` as there are still many packages that aren't migrated to null safety.

<img width="1010" alt="Screenshot 2021-05-28 at 1 08 05 AM" src="https://user-images.githubusercontent.com/22491498/119886954-2a6d6280-bf51-11eb-9ef2-c13113cae532.png">

**Comment by kevmoo** [comment]
Closing this out. Let me know if this is still an issue
