### ISSUE TITLE
Could not find a file named "pubspec.yaml" in "/home/sbr/.pub-cache/hosted/pub.dartlang.org/_fe_analyzer_shared-31.0.0".

### ISSUE THREAD

**Issue by radtki** [kevmoo/peanut.dart#128]
Hi,

I'm trying to use peanut and got the above named error message.
I run
- flutter clean
- flutter pub global activate peanut
- flutter pub get

peanut --version
4.1.1

flutter doctor -v
Flutter (Channel stable, 2.10.4, on Ubuntu 20.04.4 LTS 5.13.0-41-generic, locale de_DE.UTF-8)
    • Flutter version 2.10.4 at /home/sbr/snap/flutter/common/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision c860cba910 (vor 9 Wochen), 2022-03-25 00:23:12 -0500
    • Engine revision 57d3bac3dd
    • Dart version 2.16.2
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /home/sbr/Android/Sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /home/sbr/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✗] Chrome - develop for the web (Cannot find Chrome executable at google-chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Linux toolchain - develop for Linux desktop
    • clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
    • cmake version 3.10.2
    • ninja version 1.8.2
    • pkg-config version 0.29.1

[✓] Android Studio (version 2021.2)
    • Android Studio at /home/sbr/android-studio
    • Flutter plugin version 67.1.2
    • Dart plugin version 212.5744
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] VS Code
    • VS Code at /snap/code/current
    • Flutter extension version 3.40.0

[✓] Connected device (1 available)
    • Linux (desktop) • linux • linux-x64 • Ubuntu 20.04.4 LTS 5.13.0-41-generic

[✓] HTTP Host Availability
    • All required HTTP hosts are available

! Doctor found issues in 1 category.

**Comment by kevmoo** [comment]
That's really weird! do you get a stack trace from `peanut`? Can you share it?

**Comment by radtki** [comment]
Retry from scratch. Hopefully this will help:

**flutter pub global activate peanut**

Package peanut is currently active at version 4.1.1.
Resolving dependencies...
The package peanut is already activated at newest available version.
To recompile executables, first run `flutter pub global deactivate peanut`.
Installed executable peanut.
Warning: Executable "peanut" runs "bin/peanut.dart", which was not found in peanut.
Warning: Pub installs executables into $HOME/snap/flutter/common/flutter/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

  export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"

  **export PATH="$PATH":"$HOME/snap/flutter/common/flutter/.pub-cache/bin"**

peanut --verbose
[pub_log.txt](https://github.com/kevmoo/peanut.dart/files/8770776/pub_log.txt)

**Comment by radtki** [comment]
Just use flutter pub global run peanut instead on peanut and it works
