### ISSUE TITLE
peanut does not invode flutter build web

### ISSUE THREAD

**Issue by white-gecko** [kevmoo/peanut.dart#135]
Similar to the case of https://github.com/kevmoo/peanut.dart/issues/95 

flutter is not detected when running on github actions and installing flutter with https://github.com/subosito/flutter-action . 

The MWE for my case is basically https://github.com/white-gecko/flutter_peanut_mwe.

The `FLUTTER_ROOT` is `/opt/hostedtoolcache/flutter/stable-3.0.5-x64`.

It terminates with:

```
Validating packages:
  /home/runner/work/flutter_peanut_mwe/flutter_peanut_mwe
You must have a dependency on `build_runner` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_runner: >=1.3.0 <3.0.0
You must have a dependency on `build_web_compilers` in `pubspec.yaml`.
# pubspec.yaml
dev_dependencies:
  build_web_compilers: >=1.2.0 <4.0.0
pub finished with exit code 78
```
The complete log is: [rawlog.txt](https://github.com/kevmoo/peanut.dart/files/9385474/rawlog.txt)

But as I understand it, it should not be asking for `build_runner` and `build_web_compilers` if it would run `flutter build web`.

**Comment by kevmoo** [comment]
What's in your pubspec?

**Comment by kevmoo** [comment]
does `flutter doctor` work from the same directory?

**Comment by kevmoo** [comment]
@white-gecko – any more info here?

**Comment by white-gecko** [comment]
Sorry for not reacting, its all available here: https://github.com/white-gecko/flutter_peanut_mwe/

The error can be seen here: https://github.com/white-gecko/flutter_peanut_mwe/actions/runs/3947810376/jobs/6757067464

I've added a `flutter doctor` step now, lets see, what it says.

**Comment by white-gecko** [comment]
`flutter doctor` looks fine so far: https://github.com/white-gecko/flutter_peanut_mwe/actions/runs/3947850234/jobs/6757155847

**Comment by kateile** [comment]
I have the same problem in Github action. Locally everything works fine. Maybe there is bug in https://github.com/subosito/flutter-action.

@white-gecko have you found the exactly problem?

**Comment by white-gecko** [comment]
No, I did not.
I just created my own script to checkout the deployment branch to a temporary folder and commit the new build to that branch.

**Comment by kevmoo** [comment]
I've been very busy looking at I/O things. I'll see if I can dig in here soon. Thanks for your patience!

**Comment by kevmoo** [comment]
Is there no web app? It may be failing without a web app. 

The runs that you point to here have expired @white-gecko – could you re-run?

**Comment by white-gecko** [comment]
https://github.com/white-gecko/flutter_peanut_mwe/actions/runs/4909480765

**Comment by kevmoo** [comment]
Just for sanity sake, @white-gecko – would you copy-paste the `pubspec.yaml` file here?

**Comment by kevmoo** [comment]
@white-gecko – any way you could download and try out https://github.com/kevmoo/peanut.dart/pull/158 ??

I'd LOVE to make sure this fixes things for you

**Comment by kevmoo** [comment]
v5 is out! Let me know if it helps

**Comment by white-gecko** [comment]
Thank you! Sorry for not reacting earlier. Since I had adjusted the workflow already it is no simple drop in.
