### ISSUE TITLE
Peanut doesn't support Dart 3.0

### ISSUE THREAD

**Issue by mikhael28** [kevmoo/peanut.dart#149]
Getting this issue when trying to build and push a bundle with peanut. 

`peanut as globally activated doesn't support Dart 3.0.0-259.0.dev, try: flutter pub global activate peanut`

The error message doesn't really help - is it an easy fix to update this?

**Comment by kevmoo** [comment]
Are you running from a Dart SDK or a Flutter SDK?
What command are you invoking?

**Comment by mikhael28** [comment]
Flutter SDK, using the `master` channel to access the Dart 3.0 alpha. 
Using the command `flutter pub global run peanut:peanut --extra-args "--base-href=/mobile/" && git push origin --set-upstream gh-pages` yields `peanut as globally activated doesn't support Dart 3.0.0-259.0.dev, try: flutter pub global activate peanut`

**Comment by kevmoo** [comment]
Does `flutter pub global activate peanut` work?

**Comment by kevmoo** [comment]
Closing out. I'm running great on Dart 3. Let me know!
