### ISSUE TITLE
--post-build-dart-script seems not working

### ISSUE THREAD

**Issue by westlinkin** [kevmoo/peanut.dart#154]
Hi, 

First of all, Great work! 

This is the command I run `peanut -b webapp --web-renderer html --post-build-dart-script ./post_peanut_build.dart` 

I need to perform tree-shaking icons on web, unfortunately, the `flutter build web` does not support this option very well.  
So I build an android apk (with tree shaking) first, then replace the otf/ttf files with the ones created by `flutter build web`. This `post_peanut_build.dart` do the replace job.

```
// post_peanut_build.dart

import 'dart:io';

///
/// cp -r ./build/app/intermediates/flutter/release/flutter_assets/fonts ./build/web/assets
/// cp -r ./build/app/intermediates/flutter/release/flutter_assets/packages ./build/web/assets
///

void copyDirectory(Directory source, Directory destination) {
  destination.createSync();

  source.listSync().forEach((FileSystemEntity entity) {
    if (entity is File) {
      final newFile =
          File('${destination.path}/${entity.path.split('/').last}');
      entity.copySync(newFile.path);
    }
    else if (entity is Directory) {
      final newDir =
          Directory('${destination.path}/${entity.path.split('/').last}');
      copyDirectory(entity, newDir);
    }
  });
}

void main(List<String> args) async {
  final fontsDir = Directory(
      './build/app/intermediates/flutter/release/flutter_assets/fonts');
  final packagesDir = Directory(
      './build/app/intermediates/flutter/release/flutter_assets/packages');
  final webAssetsDir = Directory('./build/web/assets');

  webAssetsDir.createSync(recursive: true);

  if (fontsDir.existsSync()) {
    final fontsDestDir = Directory('${webAssetsDir.path}/fonts');
    copyDirectory(fontsDir, fontsDestDir);
  }

  if (packagesDir.existsSync()) {
    final packagesDestDir = Directory('${webAssetsDir.path}/packages');
    copyDirectory(packagesDir, packagesDestDir);
  }
}

```

After the peanut command is done, I notice the otf/ttf files in `./build/web` are replaced (smaller), but the files on `webapp` branch are still the larger files. 

Can you provide some instructions on how to achieve that? Or am I using the `--post-build-dart-script` option wrong.

Thanks in advance.

**Comment by kevmoo** [comment]
I'd recommend trying out the latest stable release of Flutter...soon...the font bits should be fixed!
