### ISSUE TITLE
Support build wasm option

### ISSUE THREAD

**Issue by nploi** [kevmoo/peanut.dart#176]
Hi @kevmoo, is there any way to build wasm?
I tried to build wasm using cli
```
flutter pub global run peanut -b prod-branch --extra-args "--wasm"
```
But got error
```
"--web-renderer" cannot be combined with "--wasm"
```
It would be great if we could build wasm options like this:
```
flutter pub global run peanut -b prod-branch --wasm
```

Thank you.

**Comment by kevmoo** [comment]
Although it's a bit weird because you can't get wasm to run on GitHub. You need to tweak your headers.

**Comment by nploi** [comment]
> Although it's a bit weird because you can't get wasm to run on GitHub. You need to tweak your headers.

yeah, i don't run on Github page, i want to get wasm to run on Cloudflare.
