### ISSUE TITLE
`peanut` command invalidates subsequent builds?

### ISSUE THREAD

**Issue by jakemac53** [kevmoo/peanut.dart#21]
Not sure whats going on here exactly but if I run peanut then it kills my dev server because the build script gets invalidated, and then the next build is a non-incremental build.

**Comment by jakemac53** [comment]
Note this is happening on windows, haven't checked linux/osx

**Comment by kevmoo** [comment]
I'm just running `pub run build_runner`...perhaps this is a bug in pbr on Windows?

**Comment by jakemac53** [comment]
Actually I think this is a general issue with build_runner, closing

**Comment by jakemac53** [comment]
https://github.com/dart-lang/build/issues/1331
