### ISSUE TITLE
Not working with nested packages

### ISSUE THREAD

**Issue by andresaraujo** [kevmoo/peanut.dart#26]
For https://github.com/andresaraujo/timeago.dart which has two dart packages `timeago` and `timeago_flutter` I wanted to build the web example under `timeago/example` but didn't work, it didn't produce the index.html and js outputs.

The command I used was:

// from `timeago` folder
`peanut -d example`

Am I missing something?

**Comment by kevmoo** [comment]
Ooo...good bug. Will investigate.

**Comment by kevmoo** [comment]
@andresaraujo – out of curiosity. How'd you find `peanut`?

**Comment by kevmoo** [comment]
Oh! Did you look at your branches? This will create a new branch called `gh-pages` in your repo to publish to https://pages.github.com/

**Comment by andresaraujo** [comment]
I found peanut a few years ago(2015-2016), I might found it by looking at `https://pub.dartlang.org` when it showed the newest updated packages first.

Btw I just checked out again, not a bug it did work! not sure why I though it did not create the files.

Closing thanks! @kevmoo
