### ISSUE TITLE
use peanut to drive dartdoc as well?

### ISSUE THREAD

**Issue by devoncarew** [kevmoo/peanut.dart#4]
I've run into this use case a few times, where I want to run `dartdoc` on the master branch, then copy the results (from `doc/api/`, or sometimes all of `doc`) into the gh-pages branch. It's really convenient to be able to serve your project's dartdoc output on gh-pages, but takes a bunch of git steps to get there. Seems like exactly what you're doing with peanut, but oriented towards pub build instead of dartdoc.

**Comment by devoncarew** [comment]
perhaps a `--dartdoc` or `--docs` flag

**Comment by kevmoo** [comment]
Sure! Sorry – for some reason I wasn't paying 'watching' this repo.

Pull requests welcome.

**Comment by kevmoo** [comment]
Not super interested in this personally – PRs welcome.
