### ISSUE TITLE
HELP! How to UPDATE my GitHub web page

### ISSUE THREAD

**Issue by Wizpna** [kevmoo/peanut.dart#61]
I built a portfolio website using flutter web, my portfolio website was deployed to GitHub webpage using Peanut.

I did an updates to my portfolio project, but the update I made is not reflecting on my portfolio website.

Please what should I do so that my GitHub portfolio website will be updated, your suggestions and recommendations are welcome.

**Comment by kevmoo** [comment]
Send me a link to your GitHub repo? Sometime it takes some time for it to show up...

**Comment by Wizpna** [comment]
Thanks for your feedback, I solved my problem by running this command "git push origin --set-upstream gh-pages"
