### ISSUE TITLE
ERROR: Wrong full snapshot version, expected 'a2967d784bf01190add298db8b62285b' found '1d7acad1540192ac459cf60344efb7c1' Isolate creation failed

### ISSUE THREAD

**Issue by Wizpna** [kevmoo/peanut.dart#64]
Thanks for your awesome package, I appreciate.

when i open my terminal and type: pub global activate peanut

I recieve this error message: Wrong full snapshot version, expected 'a2967d784bf01190add298db8b62285b' found '1d7acad1540192ac459cf60344efb7c1'
Isolate creation failed

Please, I need feedback on how to resolve this issue.

**Comment by kevmoo** [comment]
try `pub global deactivate peanut` then run `pub global activate peanut` again

If that doesn't work, try using `pub global activate peanut --verbose` and paste in the whole output.

Which version of Dart are you using?

**Comment by Wizpna** [comment]
Thanks for your feedback.

I tried pub global deactivate peanut and i displayed an  error message:
Wrong full snapshot version, expected 'a2967d784bf01190add298db8b62285b' found '1d7acad1540192ac459cf60344efb7c1'

I tried pub global activate peanut --verbose as well and it displayed:
Wrong full snapshot version, expected 'a2967d784bf01190add298db8b62285b' found '1d7acad1540192ac459cf60344efb7c1'
Isolate creation failed

My Dart version is 2.4.1

I will love to hear your feedback soon.

**Comment by natebosch** [comment]
Does your `pub` command work in any context? Can you `pub --help` for instance?

Something could be broken in your dart install...
