### ISSUE TITLE
"build web" is not currently supported.

### ISSUE THREAD

**Issue by JerinFrancisA** [kevmoo/peanut.dart#67]
"build web" is not currently supported.
pub failed (1)

After Flutter v1.9 flutter build web cmd has been removed.
Therefore, the "peanut" command is not working as it tries to run "build web" command.

```
 flutter pub  global run peanut
Validating packages:
  C:\Users\Jerin Francis\IdeaProjects\jerinfrancis_website

Package:     C:\Users\Jerin Francis\IdeaProjects\jerinfrancis_website
Directories: web
Command:     flutter build web

Deleting 'build\'.
Deleting 'C:\Users\Jerin Francis\IdeaProjects\jerinfrancis_website\.dart_tool\'.
Deleting 'C:\Users\Jerin Francis\IdeaProjects\jerinfrancis_website\.android\'.
Deleting 'C:\Users\Jerin Francis\IdeaProjects\jerinfrancis_website\.ios\'.
"build web" is not currently supported.
Error running "C:\Users\Jerin Francis\flutter\bin\flutter.bat build
web"
Exit code 1
```

**Comment by kevmoo** [comment]
Are you using the latest flutter on master AND the latest peanut?

**Comment by onatcipli** [comment]
@kevmoo I'm also getting this error when I try to run `peanut `command, What did I try so far

> Validating packages:
>   C:\projects\flutter_animasyon_sunum
> Could not find a file named "pubspec.yaml" in "C:\Users\Onat.cipli\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\provider-3.1.0+1".
> 

flutter doctor : 

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v1.12.11, on Microsoft Windows [Version 10.0.17763.615], locale en-GB)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.1)
[√] Chrome - develop for the web
[!] Android Studio (version 3.4)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Android Studio (version 3.5)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] IntelliJ IDEA Ultimate Edition (version 2019.2)
[√] VS Code (version 1.40.1)
[√] Connected device (2 available)

! Doctor found issues in 2 categories.

```

**Comment by ThinkDigitalSoftware** [comment]
Yeah, try switching to master

**Comment by onatcipli** [comment]
@ThinkDigitalSoftware switching to master didn't work for me

**Comment by ThinkDigitalSoftware** [comment]
You have to also enable web support.
https://flutter.dev/docs/get-started/web#enable-web-support

**Comment by onatcipli** [comment]
Already enabled! @ThinkDigitalSoftware

**Comment by ThinkDigitalSoftware** [comment]
Hmm. And you ran flutter create in the directory?

**Comment by Jayvirrathi** [comment]
**peanut command issue**

**Flutter (Channel beta, v1.12.13+hotfix.6)**

**ISSUES**


**Unsupported operation: Cannot extract a file path from a c URI
#0      _Uri.toFilePath (dart:core/uri.dart:2727:7)
#1      new Directory.fromUri (dart:io/directory.dart:152:59)
#2      copyFilesRecursive (package:peanut/src/flutter.dart:59:29)
<asynchronous suspension>
#3      runFlutterBuild (package:peanut/src/flutter.dart:44:9)
<asynchronous suspension>
#4      run (package:peanut/src/peanut.dart:123:15)
<asynchronous suspension>
#5      main (file:///C:/Flutter/flutter/.pub-cache/hosted/pub.dartlang.org/peanut-3.4.2/bin/peanut.dart:54:11)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:305:32)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)**

**Comment by kevmoo** [comment]
I'm guessing we're hitting an issue w/ running on Windows – something I haven't tested...hrm...

**Comment by Jayvirrathi** [comment]
### **Still not resolved** 

@kevmoo

**Comment by kevmoo** [comment]
Keep in mind this is a personal project and I don't have ready access to a Windows machine. 😄
