### ISSUE TITLE
Thoughts on adding support for building with package build_runner?

### ISSUE THREAD

**Issue by nshahan** [kevmoo/peanut.dart#8]
Behind a flag?
As the new default?
How to support release and debug modes?

**Comment by kevmoo** [comment]
100% support it. Pull requests welcome. Happy to chat about it tomorrow at
work...

**Comment by kevmoo** [comment]
Done! https://github.com/kevmoo/peanut.dart/commit/825e1aaba31b089b9410025fd36a6c6bfc952ded
