### ISSUE TITLE
Create Github pages for Private Repo

### ISSUE THREAD

**Issue by bhavikvashi1804** [kevmoo/peanut.dart#84]
I am not able to create Github pages for my app.
I have checked by creating two dummy projects on Github.
 I have created one project which is public and another one which is private.
I'm writing the same code for both to create Github pages.
but for private repo, it does not create the environment.

**Comment by kevmoo** [comment]
Trying going through the description and video here? https://medium.com/@kevmoo/show-off-your-flutter-dart-web-app-with-peanut-c0307f2b733c
