### ISSUE TITLE
'peanut' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by kamrancr7** [kevmoo/peanut.dart#85]
when i change code in my master branch then when i run 'peanut' command then it shows me following error.
'peanut' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kevmoo** [comment]
Have you run `pub global activate peanut`?

Have you tried running `pub global run peanut`?

**Comment by kamrancr7** [comment]
Issue has been solved after setting dart path in environment variable
