### ISSUE TITLE
404 error on github pages 

### ISSUE THREAD

**Issue by bhavikvashi1804** [kevmoo/peanut.dart#86]
https://github.com/bhavikvashi1804/flutter_BLoC_Weather_App

Check this repo I have performed all the operation listed on Package
Still Getting error on publishing pages
https://bhavikvashi1804.github.io/flutter_BLoC_Weather_App

Operation Performed: -
flutter pub global activate peanut
flutter pub global run peanut:peanut
git push origin --set-upstream gh-pages

**Comment by bhavikvashi1804** [comment]
I have chosen the theme in Github settings and it working
So What is the problem with the package?

**Comment by kevmoo** [comment]
Looks like it's up now!

**Comment by kevmoo** [comment]
Sometimes it takes a while for the first publish.

Have you tried agaian?
